docs: add sphinx-apidoc to generate api docs
Signed-off-by: Spiros Delviniotis <spirosdelviniotis@gmail.com>

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -15,13 +15,16 @@ SPHINXOPTS    =
 SPHINXBUILD   = sphinx-build
 PAPER         =
 BUILDDIR      = _build
+SOURCEDIR     = _source
+CODEDIR       = ../hepcrawl
 
 # Internal variables.
 PAPEROPT_a4     = -D latex_paper_size=a4
 PAPEROPT_letter = -D latex_paper_size=letter
-ALLSPHINXOPTS   = -nNW -d $(BUILDDIR)/doctrees $(PAPEROPT_$(PAPER)) $(SPHINXOPTS) .
+ALLSPHINXOPTS   = -d $(BUILDDIR)/doctrees $(PAPEROPT_$(PAPER)) $(SPHINXOPTS) .
 # the i18n builder cannot share the environment and doctrees with the others
 I18NSPHINXOPTS  = $(PAPEROPT_$(PAPER)) $(SPHINXOPTS) .
+SPHINXAPIDOC    = sphinx-apidoc -f -o $(SOURCEDIR) $(CODEDIR)
 
 .PHONY: help
 help:
@@ -53,15 +56,27 @@ help:
 	@echo "  coverage   to run coverage check of the documentation (if enabled)"
 	@echo "  dummy      to check syntax errors of document sources"
 
+
+# function sets exit code for html target
+define report_result_html
+	if [ -s "$(1)" ]; \
+	then \
+		echo Build Failed. Check documentation_errors.log file for details.; \
+		exit 1; \
+	fi
+endef
+
+
 .PHONY: clean
 clean:
-	rm -rf $(BUILDDIR)/*
+	rm -rf $(BUILDDIR) $(SOURCEDIR) documentation_errors.log
 
 .PHONY: html
 html:
-	$(SPHINXBUILD) -b html $(ALLSPHINXOPTS) $(BUILDDIR)/html
-	@echo
-	@echo "Build finished. The HTML pages are in $(BUILDDIR)/html."
+	$(SPHINXAPIDOC); \
+	rm -f $(SOURCEDIR)/modules.rst; \
+	$(SPHINXBUILD) -w documentation_errors.log -b html $(ALLSPHINXOPTS) $(BUILDDIR)/html
+	@$(call report_result_html,documentation_errors.log)
 
 .PHONY: dirhtml
 dirhtml:
